# Generated by Django 5.2.4 on 2025-08-26 10:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_stage',
        ),
        migrations.RemoveField(
            model_name='application',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_national_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_national_id_picture',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='companydoc',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='companydoc',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='companydoc',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='companydoc',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='job',
            name='field',
        ),
        migrations.RemoveField(
            model_name='job',
            name='openings_available',
        ),
        migrations.RemoveField(
            model_name='project',
            name='actual_end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='actual_start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='planned_end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='planned_start_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='national_id_picture',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id_picture',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_of_study',
        ),
        migrations.RemoveField(
            model_name='studentdoc',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='studentdoc',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='studentdoc',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='taskupdate',
            name='progress_percent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='application',
            name='applicationStage',
            field=models.CharField(blank=True, db_column='applicationStage', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='appliedAt',
            field=models.DateTimeField(auto_now_add=True, db_column='appliedAt', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, db_column='cv', null=True, upload_to='applications/cvs/'),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, db_column='email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='fullName',
            field=models.CharField(blank=True, db_column='fullName', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewedAt',
            field=models.DateTimeField(blank=True, db_column='reviewedAt', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewedBy',
            field=models.CharField(blank=True, db_column='reviewedBy', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='telephone',
            field=models.CharField(blank=True, db_column='telephone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='companyEmail',
            field=models.EmailField(blank=True, db_column='companyEmail', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='companyName',
            field=models.CharField(blank=True, db_column='companyName', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contactNumber',
            field=models.CharField(blank=True, db_column='contactNumber', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contactPerson',
            field=models.CharField(blank=True, db_column='contactPerson', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='companydoc',
            name='documentType',
            field=models.CharField(blank=True, db_column='documentType', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companydoc',
            name='fileUrl',
            field=models.CharField(blank=True, db_column='fileUrl', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companydoc',
            name='rejectionReason',
            field=models.TextField(blank=True, db_column='rejectionReason', null=True),
        ),
        migrations.AddField(
            model_name='companydoc',
            name='verificationStatus',
            field=models.CharField(blank=True, db_column='verificationStatus', default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='major',
            field=models.CharField(blank=True, choices=[('cs', 'Computer Science'), ('it', 'Information Tecnology'), ('eng', 'Engineering'), ('bus', 'Business'), ('edu', 'Education')], db_column='major', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='openingsAvailable',
            field=models.PositiveSmallIntegerField(blank=True, db_column='openingsAvailable', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='project',
            name='actualEndDate',
            field=models.DateField(blank=True, db_column='actualEndDate', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='actualStartDate',
            field=models.DateField(blank=True, db_column='actualStartDate', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='plannedEndDate',
            field=models.DateField(blank=True, db_column='plannedEndDate', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='plannedStartDate',
            field=models.DateField(blank=True, db_column='plannedStartDate', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dateOfBirth',
            field=models.DateField(blank=True, db_column='dateOfBirth', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fullName',
            field=models.CharField(blank=True, db_column='fullName', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='idPicture',
            field=models.ImageField(blank=True, db_column='idPicture', null=True, upload_to='studentIds/'),
        ),
        migrations.AddField(
            model_name='student',
            name='nationalId',
            field=models.ImageField(blank=True, db_column='nationalId', null=True, upload_to='studentIds/national/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profilePicture',
            field=models.ImageField(blank=True, db_column='profilePicture', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='student',
            name='studentId',
            field=models.ImageField(blank=True, db_column='studentId', null=True, upload_to='studentIds/'),
        ),
        migrations.AddField(
            model_name='student',
            name='yearOfStudy',
            field=models.PositiveSmallIntegerField(blank=True, db_column='yearOfStudy', null=True),
        ),
        migrations.AddField(
            model_name='studentdoc',
            name='documentType',
            field=models.CharField(blank=True, db_column='documentType', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentdoc',
            name='fileName',
            field=models.CharField(blank=True, db_column='fileName', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentdoc',
            name='fileUrl',
            field=models.CharField(blank=True, db_column='fileUrl', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assignedBy',
            field=models.CharField(blank=True, db_column='assignedBy', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='dueDate',
            field=models.DateField(blank=True, db_column='dueDate', null=True),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='progressPercent',
            field=models.PositiveSmallIntegerField(blank=True, db_column='progressPercent', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletedAt',
            field=models.DateTimeField(blank=True, db_column='deletedAt', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='failedAttempts',
            field=models.PositiveSmallIntegerField(db_column='failedAttempts', default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(blank=True, db_column='lastLogin', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resetToken',
            field=models.CharField(blank=True, db_column='resetToken', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tokenExpiry',
            field=models.DateTimeField(blank=True, db_column='tokenExpiry', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='comments',
            field=models.TextField(blank=True, db_column='comments', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(db_column='attachmentId', on_delete=django.db.models.deletion.RESTRICT, to='core.job'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_column='status', default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, db_column='industry', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, db_column='location', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(db_column='loginId', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, db_column='website', null=True),
        ),
        migrations.AlterField(
            model_name='companydoc',
            name='company',
            field=models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, db_column='deadline', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, db_column='description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.CharField(blank=True, choices=[('1-month', '1 Month'), ('3-months', '3 Months'), ('6-months', '6 Months'), ('1-year', '1 Year'), ('permanent', 'Permanent')], db_column='duration', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, db_column='location', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], db_column='status', default='open', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(blank=True, choices=[('fullTime', 'Full Time'), ('partTime', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], db_column='type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='application',
            field=models.ForeignKey(db_column='applicationId', on_delete=django.db.models.deletion.RESTRICT, to='core.application'),
        ),
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.TextField(blank=True, db_column='comments', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, db_column='description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(db_column='status', default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='comments',
            field=models.TextField(blank=True, db_column='comments', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(blank=True, choices=[('cs', 'Computer Science'), ('it', 'Information Tecnology'), ('eng', 'Engineering'), ('bus', 'Business'), ('edu', 'Education')], db_column='major', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(blank=True, db_column='telephone', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(db_column='university', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(db_column='loginId', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentdoc',
            name='application',
            field=models.ForeignKey(db_column='applicationId', on_delete=django.db.models.deletion.CASCADE, to='core.application'),
        ),
        migrations.AlterField(
            model_name='studentdoc',
            name='student',
            field=models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, db_column='description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(db_column='status', default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='comments',
            field=models.TextField(blank=True, db_column='comments', null=True),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='student',
            field=models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='task',
            field=models.ForeignKey(db_column='taskId', on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_column='email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_column='is_staff', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(db_column='is_superuser', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('company', 'Company'), ('admin', 'Admin')], db_column='role', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], db_column='status', default='active', max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='companydoc',
            table='companyDocs',
        ),
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
        migrations.AlterModelTable(
            name='studentdoc',
            table='studentDocs',
        ),
        migrations.AlterModelTable(
            name='taskupdate',
            table='taskUpdate',
        ),
        migrations.CreateModel(
            name='StudentResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
    ]
