# Generated by Django 5.2.4 on 2025-08-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_application_application_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='idPicture',
        ),
        migrations.AlterField(
            model_name='student',
            name='nationalId',
            field=models.ImageField(blank=True, db_column='nationalId', null=True, upload_to='nationalIds/'),
        ),
    ]
