# Generated by Django 5.2.4 on 2025-09-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_reset_token_user_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='companyEmail',
        ),
    ]
