# Generated by Django 5.2.4 on 2025-08-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_student_idpicture_alter_student_nationalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(blank=True, choices=[('cs', 'Computer Science'), ('it', 'Information Technology'), ('eng', 'Engineering'), ('bus', 'Business'), ('edu', 'Education')], db_column='major', max_length=50, null=True),
        ),
    ]
