# Generated by Django 5.2.4 on 2025-08-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='task_proofs/'),
        ),
    ]
