# Generated by Django 5.2.4 on 2025-08-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_isaccepted_taskupdate_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskupdate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_column='status', default='pending', max_length=20),
        ),
    ]
