# Generated by Django 5.2.4 on 2025-08-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_taskupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskupdate',
            name='reviewedAt',
            field=models.DateTimeField(blank=True, db_column='reviewedAt', null=True),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='submittedAt',
            field=models.DateTimeField(auto_now_add=True, db_column='submittedAt', null=True),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='proof',
            field=models.FileField(blank=True, db_column='proof', null=True, upload_to='task_proofs/'),
        ),
    ]
