# Generated by Django 5.2.4 on 2025-08-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_taskupdate_reviewedat_taskupdate_submittedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
