# Generated by Django 5.2.4 on 2025-09-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_taskupdate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskupdate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
