# Generated by Django 5.2.4 on 2025-09-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_taskupdate_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cv',
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.studentresume'),
        ),
    ]
