# Generated by Django 5.2.4 on 2025-09-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_application_cv_application_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresume',
            old_name='name',
            new_name='fullName',
        ),
    ]
