# Generated by Django 5.2.4 on 2025-09-07 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_name_studentresume_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupdate',
            name='task',
            field=models.ForeignKey(db_column='taskId', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.task'),
        ),
    ]
