# Generated by Django 5.2.4 on 2025-09-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_taskupdate_task'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentresume',
            table='"studentResume"',
        ),
    ]
