# Generated by Django 5.2.4 on 2025-09-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_studentresume_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
