# Generated by Django 5.2.4 on 2025-09-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_company_companylogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, db_column='location', max_length=150, null=True),
        ),
    ]
