# Generated by Django 5.2.4 on 2025-09-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_student_location'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentresume',
            table='studentResume',
        ),
    ]
